package com.csye6225.fall2019.courseservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Announcement")
public class Announcement {
	@DynamoDBAutoGeneratedKey
	private String id;
	@DynamoDBHashKey(attributeName = "announcementId")
	private String announcementId;
	private String announcementText;
	private String boardId;
	
	public Announcement() {
		
	}

	public Announcement(String announcementId, String announcementText, String boardId) {
		this.announcementId = announcementId;
		this.announcementText = announcementText;
		this.boardId = boardId;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAnnouncementId() {
		return announcementId;
	}

	public void setAnnouncementId(String announcementId) {
		this.announcementId = announcementId;
	}

	@DynamoDBAttribute(attributeName="announcementText")
	public String getAnnouncementText() {
		return announcementText;
	}

	public void setAnnouncementText(String announcementText) {
		this.announcementText = announcementText;
	}

	@DynamoDBAttribute(attributeName = "boardId")
	public String getBoardId() {
		return boardId;
	}

	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}

	@Override
	public String toString() {
		return "Announcement [id=" + id + ", announcementId=" + announcementId + ", announcementText="
				+ announcementText + ", boardId=" + boardId + "]";
	}
	
}
