package com.csye6225.fall2019.courseservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Board")
public class Board {
	@DynamoDBAutoGeneratedKey
	private String id;
	@DynamoDBHashKey(attributeName = "boardId")
	private String boardId;
	private String courseId;
	
	public Board() {
		
	}

	public Board(String boardId, String courseId) {
		this.boardId = boardId;
		this.courseId = courseId;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBoardId() {
		return boardId;
	}

	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}

	public String getCourseId() {
		return courseId;
	}

	@DynamoDBAttribute(attributeName = "courseId")
	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	@Override
	public String toString() {
		return "Board [id=" + id + ", boardId=" + boardId + ", courseId=" + courseId + "]";
	}
	
	
}
