package com.csye6225.fall2019.courseservice.model;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Course")
public class Course {
	@DynamoDBAutoGeneratedKey 
	private String id;
	@DynamoDBHashKey(attributeName = "courseId")
	private String courseId;
	private String professorId;
	private String taId;
	private String departmentId;
	private String boardId;
	private List<String> roster;	
	
	public Course() {
		
	}

	public Course(String courseId, String professorId, String taId, String departmentId, List<String> roster, String boardId) {
		this.courseId = courseId;
		this.professorId = professorId;
		this.taId = taId;
		this.departmentId = departmentId;
		this.roster = roster;
		this.boardId = boardId;
	}
	
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCourseId() {
		return courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}
	
	@DynamoDBAttribute(attributeName = "professorId")
	public String getProfessorId() {
		return professorId;
	}

	public void setProfessorId(String professorId) {
		this.professorId = professorId;
	}

	@DynamoDBAttribute(attributeName = "taId")
	public String getTaId() {
		return taId;
	}

	public void setTaId(String taId) {
		this.taId = taId;
	}

	@DynamoDBAttribute(attributeName = "departmentId")
	public String getDepartmentId() {
		return departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}

	@DynamoDBAttribute(attributeName = "roster")
	public List<String> getRoster() {
		return roster;
	}

	public void setRoster(List<String> roster) {
		this.roster = roster;
	}

	@DynamoDBAttribute(attributeName = "boardId")
	public String getBoardId() {
		return boardId;
	}

	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}

	@Override
	public String toString() {
		return "Course [id=" + id + ", courseId=" + courseId + ", professorId=" + professorId + ", taId=" + taId
				+ ", departmentId=" + departmentId + ", boardId=" + boardId + ", roster=" + roster + "]";
	}

}
